# -*- coding: utf-8 -*-
"""Conditional_Statements.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fp4GJ5QQC992ftpTkY0KCJedmsCtqWl
"""

# 1st Question :

 #1.if battery bassed toys - discount 10% >1000
 #2.if key based toys - 5% discount > 100
 #3.if electrical based toys - 10% if amount > 500

# Example 1

print('1. Battery Based toys')
print('2.Key - Based Toys')
print('3.Electrical Charging based toys ')

code = int(input('enter the code (1/2/3)'))
amount = int(input("enter the amount : "))
if code == 1:
  if amount > 1000:
    discount = amount * 0.1

elif code ==2:
  if amount > 100:
    discount = amount * 0.05

elif code == 3:
  if amount > 500:
    discount = amount * 0.1
else:
  print("Invalide Produt code")
net_amount = amount - discount
print()
print('Discount : ',discount)
print('Net Amount: ',net_amount)

#Example 2

a = int(input('Enter the value of a: '))
b = int(input('Enter the value of b: '))
c = int(input('Enter the value of c: '))
d = int(input('Enter the value of d: '))
k = int(input('Enter the value of k: '))
x = int(input('Enter the value of x: '))

if x > k:
  formula = a*x**3 - b*x**2 + c*x - d
  print('f(x): ', formula)
elif x == k:
  formula = 0
  print('f(x) : ',formula)
elif x < k:
  formula = -a*x**3 + b*x**2 - c*x + d
  print('f(x) : ',formula)

# example 3

category = str(input('Enter the Category(commercial/Industrial/domestic)'))
units = int(input('Enter the Units : '))

if category == 'commercial':
  if(units >=0 and units <= 5000):
    rate = 1500
    print('Rate is :',rate)
  elif(units > 5000 and units <=10000 ):
    rate = 0.25 * units
    print('Rate is :',rate)
  elif(units >10000 and units <= 20000 ):
    rate = 0.23 *units
    print('Rate is :',rate)
  else:
    rate = 0.20 * units
    print('Rate is : ',rate)
elif category == 'institutional':
  if(units >=0 and units <=5000):
    rate = 1800
    print('Rate is :',rate)
  elif(units > 5000 and units <=10000 ):
    rate = 0.30 * units
    print('Rate is :',rate)
  elif(units >10000 and units <= 20000 ):
    rate = 0.28 *units
    print('Rate is :',rate)
  else:
    rate = 0.25 * units
    print('Rate is : ',rate)
elif category == 'domestic':
  if(units >=0 and units <=100):
    rate = 75
    print('Rate is :',rate)
  elif(units > 100 and units <=200 ):
    rate = 1.25 * units
    print('Rate is :',rate)
  elif(units >200 and units <= 400 ):
    rate = 2.00 *units
    print('Rate is :',rate)
  else:
    rate = 2.50 * units
    print('Rate is : ',rate)

# Example 4

age = int(input("Enter your age :"))
gender = str(input("enter sex(M/F) : "))
no_days = int(input("enter the Number of Days :"))
if(age >= 18 and age<30 and gender == 'M'):
  wages = no_days*700
  print('Wages : ',wages)
elif(age >= 18 and age<30 and gender == 'F'):
  wages = no_days*750
  print('Wages : ',wages)
elif(age >= 30 and age<=40 and gender == 'M'):
  wages = no_days*800
  print('Wages : ',wages)
elif(age >= 30 and age<=40 and gender == 'F'):
  wages = no_days*850
  print('Wages : ',wages)
else:
  print('Invalide age')

# Example 5

amount= int(input("enter the amount : "))
code = str(input("enter the code(sh/p/sht)"))

if (amount >=0 and amount <= 100):
  if code == 'sh':
    net_amount = amount                    #discount is 0%
    print("Amount paid by customber : ",net_amount)
  elif code == 'p':
    net_amount = amount - (0.03 *amount)   # discount is 3%
    print("Amount paid by customber : ",net_amount)
  elif code == 'sht':
    net_amount = amount - (0.05 *amount)   # discount is 5%
    print("Amount paid by customber : ",net_amount)
  else:
    print('Invalide code')

if (amount >=101 and amount <= 200):
  if code == 'sh':
    net_amount = amount - (0.05*amount)    # discount is 5%
    print("Amount paid by customber : ",net_amount)
  elif code == 'p':
    net_amount = amount - (0.08 *amount)    # discount is 8%
    print("Amount paid by customber : ",net_amount)
  elif code == 'sht':
    net_amount = amount - (0.1 *amount)      # discount is 10%
    print("Amount paid by customber : ",net_amount)
  else:
    print('Invalide code')

if (amount >=201 and amount <= 300):
  if code == 'sh':
    net_amount = amount - (0.1*amount)       #discount is 10%
    print("Amount paid by customber : ",net_amount)
  elif code == 'p':
    net_amount = amount - (0.12 *amount)     #discount is 12%
    print("Amount paid by customber : ",net_amount)
  elif code == 'sht':
    net_amount = amount -(0.15 *amount)      #discount is 15%
    print("Amount paid by customber : ",net_amount)
  else:
    print('Invalide code')

elif(amount > 300):
  if code == 'sh':
    net_amount = amount - (0.18*amount)      #discount is 18%
    print("Amount paid by customber : ",net_amount)
  elif code == 'p':
    net_amount = amount - (0.2 *amount)      #discount is 20%
    print("Amount paid by customber : ",net_amount)
  elif code == 'sht':
    discount = 0.12 *amount
    net_amount=amount - discount             #discount is 12%
    print("Discount =",discount)
    print("Amount paid by customber : ",net_amount)
  else:
    print('Invalide code')

5/100