# -*- coding: utf-8 -*-
"""Conditional statements2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nrOBTiHEBukdknvPAWmDzxwXeklwht7
"""

hungry = str(input("ask the person is hungry(yes/no) :"))

if hungry == 'yes' :
  print('Visit the Grocery!')
  cost = int(input('Enter the cost of the chocalates'))
  if cost <=1:
    print('Buy three chocalate')
  else:
    print('Buy one chocalate')
elif hungry == 'no':
    print('Ask them to stay home!')
    play = str(input("Do you play any games : "))
    if play == 'yes':
      print('See you next week')
    else:
      print('go back to studing')
      study = str(input('Are you interested to study(yes) : '))
      if study == 'yes':
        subject = str(input('What is your fav subject : '))
        if subject == 'history':
          print("It is my fav subject too! ")
        else:
          print('We dont hve any common term between us')
      else:
        print("Invalide user input")
else:
  print("invalide user input")

name = str(input("enter your name :"))
department = str(input("enter the department(HR/IT/Operetions) :"))
service =int(input("enter the years of experience : "))
salary = int(input("enter the salary : "))
bonus = 0
if department == 'HR':
  if service < 5:
    bonus = 0.08 *salary +5000
  else:
    bonus = 0.12 * salary+ 5000
elif department == 'IT':
  if service < 5:
    bonus = 0.1 *salary +6000
  else:
    bonus = 0.15*salary +6000
elif department == 'Operetions':
  if service < 5:
    bonus = 0.07*salary+4500
  else:
    bonus=0.1*salary + 4500
else:
  print("Invalide user input")
print()
print("Employee Name : ", name)
print("Employee Department : ",department)
print("Total Bonus :",bonus)