# -*- coding: utf-8 -*-
"""Python-Mayuri

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0Qhewr33flCuyy-6MEGV3FNfFJG9Jq4
"""

# PYTHON Basics

# print statement
print("hello,I am Mayui")



a = 45
b=  "10"
c= 6
print(a,b,c)

b= 3
sum  = a+b
print( sum)
diff = a-b
mul=a*b
div=a/b
fd=a//b
print(diff, mul,div,fd)

a = float(input("entr value of a : "))
b = float(input("entr value of b : "))
c = a + b
print("sum of a and b: ", c)

a = float(input("entr value of a : "))
b = float(input("entr value of b : "))
c = a - b
print("substraction of a and b: ", c)

a = float(input("entr value of a : "))
b = float(input("entr value of b : "))
c = a * b
print("mul of a and b: ", c)

# DIVISION:
a = float(input("entr value of a : "))
b = float(input("entr value of b : "))
c = a / b
print("Division of a and b: ", c)

a = float(input("entr value of a : "))
b = float(input("entr value of b : "))
c = float(input("entr value of c : "))
d = float(input("entr value of d : "))
z = a +b+c+d
y = a-b-c-d
x=a*b*c*d
w=a/b/c/d
r=a+b-c*d
print("sum of a ,b,c & d: ", z)
print("substraction of a,b,c,d: ",y)
print("multification of a,b,c&d: ", x)
print("division of a,b,c&d: ",w)
print("output =",r)

# Sample Data
name = str(input("enter name : "))
p_no = str(input("enter phone number : "))
address= str(input("enter your address : "))
age = int(input("enter your age : "))
gender = str(input("enter your gender : "))
email_id = str(input("enter your email id :"))
pin_code = int(input("enter your pincode : "))
Education = str(input("enter your current eduction : "))
# output
print("Name = ",name)
print("Phone Number is = ",p_no)
print("Address is = ",address)
print("Age is = ",age)
print("Gender is = ",gender)
print("Email ID is = ",email_id)

# Comparison Operator
a = int(input("enter value of a : "))
b= int(input("enter value of b :  "))
print("a > b :", a>b)   # greaterthan
print("a< b : ",a<b)    # lesserthan
print("a == b",a==b)    # check for equality
print("a != b", a!=b)   # check for non equality
print("a >= b", a>=b)   # greaterthan equal
print("a <= b",a<=b)    # smallerthan equal

# Logical Operators
a = 5
b = 6
print(a > b and a < b)
print(a < b or a > b)

# Assignment Operators
x = 5
x += 3
print(x)

y = 6
y -= 5
print(y)

z = 45
z *= 2
print(z)

# Membership Operetor
a = "Mayuri"
print('r' in a)
print('R' in a)
print('r' not in a)

# Conditional Statement
age = int(input("Enter your age : "))
if age>= 18:
  print("eligible for voting")
else:
  print("not eligible for voting")

cost = int(input("Enter the cost :"))
if (cost > 0 and cost <=100):
  print(" buy the product")
else:
  print("reject to buy")

"""#
1. if price betn 1 - 100 -people can buy
2. if price betn 101 - 200 - people can bargain
3.if its more than 200 - people can reject
"""

price = int(input("Enter the price : "))

if(price > 0 and price <=100):
  print("people can buy")
elif(price > 101 and price <= 200):
  print("people can bargain")
else:
  print("people reject")

marks = int(input("Enter your marks : "))
print(marks)